// Picks validated Daily Bench seeds (ChatGPT r11): a seed ships only if a random 5s novice AND the cascade bot both win it,
// so Daily never quietly becomes experts-only. Usage: npx vite-node tools/daily-seeds.ts > src/content/dailySeeds.ts
import { choosePerk, drop, legalPairs, newGame, previewMerge, tick, type GameState } from '../src/core/game';
import { Rng } from '../src/core/rng';

type Pick = (s: GameState, rng: Rng) => [number, number] | null;
const novice: Pick = (s, rng) => {
  const p = legalPairs(s);
  if (!p.length) return null;
  const [a, b] = p[rng.int(p.length)];
  return rng.next() < 0.5 ? [a, b] : [b, a];
};
const cascade: Pick = (s) => {
  let best: [number, number] | null = null;
  let bd = -1;
  for (const [a, b] of legalPairs(s))
    for (const [f, t] of [[a, b], [b, a]] as [number, number][]) {
      const d = previewMerge(s, f, t)!.total;
      if (d > bd) [bd, best] = [d, [f, t]];
    }
  return best;
};

function play(seed: number, pick: Pick, every: number, botSeed: number) {
  const s = newGame(seed, false);
  const rng = new Rng(botSeed);
  let next = every;
  while (s.phase === 'playing' || s.phase === 'choice') {
    if (s.phase === 'choice') {
      choosePerk(s, s.offer[rng.int(s.offer.length)]);
      continue;
    }
    if (s.elapsed >= next) {
      next += every;
      const m = pick(s, rng);
      if (m) drop(s, m[0], m[1], s.grid[m[0]]!.id);
    }
    tick(s);
  }
  return { won: s.phase === 'won', time: s.elapsed };
}

const out: number[] = [];
for (let seed = 20261006; out.length < 120; seed += 7919) {
  // the novice must win with 2 of 3 different bot dice, the cascade bot must win comfortably
  const nov = [1, 2, 3].filter((k) => play(seed, novice, 5, seed * 3 + k).won).length;
  const cas = play(seed, cascade, 2.5, 1);
  if (nov >= 2 && cas.won && cas.time < 110) out.push(seed >>> 0);
}
console.log(`// generated by tools/daily-seeds.ts — do not edit by hand. Bump DAILY_VERSION whenever the list or run rules change.
export const DAILY_VERSION = 3;
export const DAILY_SEEDS: number[] = [${out.join(', ')}];`);
